### ISSUE TITLE
stream output

### ISSUE THREAD

**Issue by Hoten** [coursehero/slacktee#53]
Would be super great to have slacktee stream output to Slack. It could update the comment as output comes in.

**Comment by Chikashi-Kato** [comment]
Hello Hoten!
Have you tried '-n' (--no-buffering) option? I think that is what you are looking for :)

**Comment by Hoten** [comment]
Oh, I didn't know about that feature. But not quite. One use case I have is a command that outputs useful information in the beginning of the command, followed by about 20 minutes of work, and then prints out a summary. I would like to see the beginning output when it's ready, and have the last output edited into the same comment.

I'll look into adding this myself, I just wanted to create a task to track it. Thanks Chuck! This tool has been quite useful.

-Connor

**Comment by Hoten** [comment]
```
(echo "test"; sleep 5; echo "more test") | /usr/local/bin/slacktee.sh -c connor-test-channel -n
```

![image](https://user-images.githubusercontent.com/4071474/42728594-8b772d1e-8772-11e8-8440-c081266ef32a.png)

The behavior I'd like is for the first comment to be updated with additional output. Think that's possible?

**Comment by Chikashi-Kato** [comment]
Hi Connor, thank you for giving me an example!
Now I fully understand your requirement. Unfortunately, current slacktee doesn’t have a capability to do it.
Since slacktee is using the incoming webhook for interacting to Slack (except the file upload option), I am assuming updating the existing comment isn’t trivial. 
I will research a little bit more but it would be nice you can try to find a way to do it.

Thanks!!!

**Comment by Chikashi-Kato** [comment]
The way which can be relatively easily implemented is sending a message with the next buffering but not only new line but also the lines previously input.
In your example, we will see ‘test’ and ‘more test’ as a message after the message ‘buffer’.
This way posts many redundant messages but we don’t have to implement the way updating the 1st comment.
What do you think?

**Comment by Hoten** [comment]
Hi Chuck,

I want to avoid that easy way, as I think it would end up spamming the channel.

You're right that the webhook api is lacking for this. Luckily, utilizing the regular API was simple enough. I opened a PR adding the feature.
