### ISSUE TITLE
Error: here-document delimited by end-of-file (wanted `EOF')

### ISSUE THREAD

**Issue by DannyBen** [coursehero/slacktee#57]
When running in a plain alpine container (with bash and curl installed), I was getting this error:

```
bash-4.4# slacktee
/usr/local/bin/slacktee: line 792: warning: here-document at line 406 delimited
by end-of-file (wanted `EOF')
/usr/local/bin/slacktee: line 793: syntax error: unexpected end of file
```

Removing the indentation of the closing `EOF` in this block fixes the problem:
https://github.com/coursehero/slacktee/blob/86522a9938409bb974aa353b89eb0c4ae8abc02d/slacktee.sh#L406-L415

**Comment by Chikashi-Kato** [comment]
Oh, nice catch! I have never seen that error before. If you don't mind, could you create a PR for fixing it?

**Comment by DannyBen** [comment]
Sure

**Comment by Chikashi-Kato** [comment]
Merged your PR! Thank you for fixing this issue, Danny!
