### ISSUE TITLE
color doesn't stay

### ISSUE THREAD

**Issue by boredland** [coursehero/slacktee#62]
I expected this
```
(echo "bliblablu test 123"; sleep 5; echo "blibla error kfgjk"; sleep 5)|../tools/build/gae/slacktee.sh --streaming           -o "danger" ".*error.*"           -s head das           -s env das           -s branch das           -s commit/tag abcder           -e log "https://console.cloud.google.com/cloud-build/builds/$BUILD_ID"           -c "@jonas.strassel"
```
to be a message marked red. instead it changes its color back to grey. I my expectation wrong?

**Comment by Chikashi-Kato** [comment]
So sorry for the delayed reply, @boredland . I will look into it and get back to you soon!

**Comment by Chikashi-Kato** [comment]
I confirmed the behavior. I think it's a bug of `--streaming` option.
Expected behavior is keeping the color of the last output. 

Thank you for reporting this issue, @boredland . I will work on this issue.

**Comment by Chikashi-Kato** [comment]
This issue should be fixed :) Again, sorry for the delayed reply!
