### ISSUE TITLE
Unable to close with CTRL+C, when running directly

### ISSUE THREAD

**Issue by msmyers** [coursehero/slacktee#64]
While testing out the script (amazing work, btw), I typed `slacktee.sh` in my terminal.

It gave me a warning about "using the URL is deprecated, please use token" and then it hung, with CTRL+C not aborting. I was forced to restart my terminal session.

Thoughts?

  > Running `echo "hey" | slacktee.sh` worked

**Comment by Chikashi-Kato** [comment]
Thank you for trying slacktee and reporting the issue, @msmyers!
I will test it out and get back to you.

**Comment by Chikashi-Kato** [comment]
I confirmed the behavior. `slacktee.sh` doesn't handle CTRL+C. I'm adding a signal handler to `slacktee.sh`.

BTW, we can still finish `slacktee.sh` by sending [End-of-Transmission](https://en.wikipedia.org/wiki/End-of-Transmission_character) with CTRL+D, but in this case, all of the input characters are sent to slack. Therefore, I believe support CTRL+C for abort sending message is useful.

**Comment by Chikashi-Kato** [comment]
BTW "using the URL is deprecated, please use token" is just a deprecation warning introduced at `v1.4.0` and it's not related with this issue. 
If you want to suppress it, please use `token` instead of `webhook`.

**Comment by Chikashi-Kato** [comment]
@msmyers This has been fixed with v1.4.2. Thanks again for reporting this issue!
