### ISSUE TITLE
Interactive copies won't work for unattended installs

### ISSUE THREAD

**Issue by luckytaxi** [coursehero/slacktee#66]

**Comment by connorjclark** [comment]
@luckytaxi Could you provide some more context? What commands are you running, and what is the output vs what you expect?

**Comment by Chikashi-Kato** [comment]
I think @luckytaxi mentioned about the same thing as #69.
Since #69 has been closed, I'm closing this issue as well.

Please feel free to reopen, if I misunderstand this issue.
