### ISSUE TITLE
Unable to create slacktee as a service

### ISSUE THREAD

**Issue by micruzz82** [coursehero/slacktee#68]
Hi 

This application is really useful and helps so much with a simple thing of posting a message to Slack.

I have an issue though. I am trying to run this bash script as a service.

/tmp/temp.sh
#!/bin/bash
tail -f /tmp/metrics.out | slacktee.sh -u 'snmptrap' -n

The service file is 

cat /etc/systemd/system/slack-snmp.service
[Unit]
Description= Send SNMP traps received on telegraf to slack service.

[Service]
Type=simple
ExecStart=/tmp/temp.sh

[Install]
WantedBy=multi-user.target

However on starting the service, it is not able to read the .slacktee file

systemctl status slack-snmp

● slack-snmp.service - Send SNMP traps received on telegraf to slack service.
   Loaded: loaded (/etc/systemd/system/slack-snmp.service; disabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-03-13 01:15:39 UTC; 6s ago
 Main PID: 10650 (temp.sh)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/slack-snmp.service
           ├─10650 /bin/bash /tmp/temp.sh
           └─10651 tail -f /tmp/metrics.out

Mar 13 01:15:39 snmp-trap-1 systemd[1]: Started Send SNMP traps received on telegraf to slack service..
Mar 13 01:15:39 snmp-trap-1 temp.sh[10650]: slacktee.sh: Please setup the authentication token or the incoming webhook url (deprecated).

Can you please help me how I can run this shell script as a service and show the file .slacktee

Thanks you in advance.

Great program indeed.

**Comment by connorjclark** [comment]
You're sure there is a slacktee.conf file?
```
slacktee.sh: Please setup the authentication token or the incoming webhook url (deprecated).
```

**Comment by micruzz82** [comment]
Hi @connorjclark there is an option to specify --config with the script.. once I was able to do that it is now running as a service.. thanks for your help though. Should have read the docs more closely :)

**Comment by Chikashi-Kato** [comment]
@micruzz82 
This is just for your information. 
By default, slacktee tries to read .slacktee from the home directory of the user who executes slacktee. If your service user doesn’t have the home directory, slacktee doesn’t work.
As you did, you can specify the location of .slactee with “--config” option in this case.
Another way is using “/etc/slacktee.conf”, as Conor suggested. This file works same as .slacktee but it’s a host wide configuration. If .slacktee cannot be loaded, “slacktee.conf” is used as a fallback. 
If you have multiple services which use slacktee, slacktee.conf might be a good option.
Hope this information is helpful for your future configuration.

Thank you for using slacktee!

**Comment by micruzz82** [comment]
@Chikashi-Kato thank you for the advice. So far really happy that everything works as expected! Great job on this and your team
