### ISSUE TITLE
Add ability to skip interactive setup upon installation

### ISSUE THREAD

**Issue by TeTiRoss** [coursehero/slacktee#69]
Please, add ability to skip interactive setup at the end of the installation.

**Comment by Chikashi-Kato** [comment]
Sorry, I overlooked this request. Yeah, it should be easy by adding extra option to `install.sh`

**Comment by Chikashi-Kato** [comment]
`-s`/`--skip-setup` option has been added to `install.sh` at `v1.5.0`
