### ISSUE TITLE
Breaking rich format when sending +4000 characters

### ISSUE THREAD

**Issue by marcelo321** [coursehero/slacktee#83]
I'm not sure if this is a bug or not, but when sending over 4k characters, the rich formats breaks and the message it's sent like this:

message1:
`(3)
message

message2:
abcabc
`(3)

so the rich format doesn't work and looks a bit ugly

**Comment by Chikashi-Kato** [comment]
This is the known issue and caused by the limitation of the slack API. For now, I don’t have any ideas handling this issue in better ways.
If you know that the input can exceed 4000 characters, I recommend you to use -f option which sends the input as a file.

**Comment by marcelo321** [comment]
Thanks, yeah I thought it had to do with the limit of the api
